#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

x11cfg="$XDG_CONFIG_HOME/x11"
xprofile="$x11cfg/xprofile"
xresources="$x11cfg/xresources"
colors="$XDG_CONFIG_HOME/lscolors/lscolors"

[ -f "$xprofile" ] && . $xprofile
[ -f "$colors" ] && eval `dircolors --sh "$colors"`

# No programs use xresources
[[ -f "$xresources" ]] && xrdb -merge -I$x11cfg/xres $xresources

exec dwm
