remap('n', '<A-k>', ':BufferPrevious<CR>')
remap('n', '<A-j>', ':BufferNext<CR>')
remap('n', '<A-K>', ':BufferMovePrevious<CR>')
remap('n', '<A-J>', ':BufferMoveNext<CR>')
remap('n', '<A-x>', ':BufferClose<CR>')
remap('n', '<A-s>', ':BufferPick<CR>')

local cmd = vim.cmd
cmd('hi BufferCurrent guifg=#f2e5bc guibg=none gui=bold')
cmd('hi BufferCurrentIndex guifg=#f2e5bc guibg=none')
cmd('hi BufferCurrentMod guifg=#ea6962 guibg=none')
cmd('hi BufferCurrentSign guifg=#8ec07c guibg=none')
cmd('hi BufferCurrentTarget guifg=#8ec07c guibg=none gui=bold')
cmd('hi BufferVisible guifg=#d4be98 guibg=none')
cmd('hi BufferVisibleIndex guifg=#d4be98 guibg=none')
cmd('hi BufferVisibleMod guifg=#d4be98 guibg=none')
cmd('hi BufferVisibleSign guifg=#98971a guibg=none')
cmd('hi BufferVisibleTarget guifg=#98971a guibg=none gui=bold')
cmd('hi BufferInactive guibg=#1d2021')
cmd('hi BufferInactiveIndex guifg=#d4be98 guibg=#1d2021')
cmd('hi BufferInactiveMod guifg=#d4be98 guibg=#1d2021')
cmd('hi BufferInactiveSign guifg=#ea6962 guibg=#1d2021')
cmd('hi BufferInactiveTarget guifg=#ea6962 guibg=#1d2021')
cmd('hi BufferTabpageFill guifg=#d4be98 guibg=none')
cmd('hi BufferTabpages guifg=#000000 guibg=#000000')
